# -*- coding: utf-8 -*-
"""Text generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJgAW6c1VWHaICcRgUuLRSec9oB6MeOo
"""

! pip install transformers torch

from transformers import pipeline
#Load text generation model (Gen AI)
generator=pipeline(
    "text-generation",
    model="gpt2"
)
#input prompt
prompt="Social studies"
#Generate text
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])